config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  root to: "meeting_rooms#index"
  resources :meeting_rooms do
    resources :schedules
  end
  
  get "all_schedules", to: "schedules#all_schedules", as: "all_schedules"
  mount Commontator::Engine => '/commontator'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord

    belongs_to :user
     has_many :schedules, dependent: :destroy 
     validates :name,:description, presence: true      
end

app/models/schedule.rb
class Schedule < ApplicationRecord
     belongs_to :meeting_room
     acts_as_commontator
     acts_as_commontable dependent: :destroy

     #m:n with user
      # User Associations: 
     has_and_belongs_to_many :users
     validates :name, :agenda,  presence: true     

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :meeting_rooms, dependent: :destroy
#m:n relation with schedules
has_and_belongs_to_many :schedules       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # authenticating users before accesing any path
  before_action :authenticate_user!
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :set_meeting,  only: [:show, :edit, :update, :destroy ]
  
  def index
    @meeting_rooms = MeetingRoom.all
  end

  def new
    @meeting_room = MeetingRoom.new
  end

  # Create new project & save it to database
  def create
    @meeting_room = MeetingRoom.new(room_params)
    @meeting_room.user_id = current_user.id
    if @meeting_room.save
      redirect_to meeting_rooms_path
    else
      render 'new'
    end
  end

  # Edit the exisiting project
  def edit
   
  end

  # Update the existing project 
  def update
   
    if @meeting_room.update(room_params)
      redirect_to meeting_rooms_path
    else
      render 'edit'
    end
  end
  
  # Destroy the project
  def destroy
    if @meeting_room.destroy
      redirect_to meeting_rooms_path
    else
      render 'new'
    end
  end

  private
  #strong parameters

  #set meeting rooom
  def set_meeting
    @meeting_room = MeetingRoom.find(params[:id])
  end

  def room_params
    params.require(:meeting_room).permit(:name, :description, :user_id)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_meeting_room, except: [:all_schedules]
  # before_action :set_schedule, only: [:show, :edit, :update, :destroy ]

  def index
    @schedules = @meeting_room.schedules.all
  end

  def all_schedules
    @schedules = Schedule.all
  end

  def new
    @schedule = @meeting_room.schedules.new
    commontator_thread_show(@schedule)
    @users_list = User.pluck(:email)
  end

  def show
    @schedule = @meeting_room.schedules.find(params[:id])
    commontator_thread_show(@schedule)
  end

  def create
    #create function

    @schedule = @meeting_room.schedules.new(schedule_params)
    # @schedule.user_id = current_user.id
    commontator_thread_show(@schedule)
    # @meeting.user = current_user
    # binding.pry
    # @schedule.user = current_user.id

    @users_list = User.pluck(:email)

    if @schedule.save
      # UserMailer.with(user: @user).welcome_email.deliver_later
      UserMailer.send_mail(@schedule, @users_list).deliver_now
      redirect_to meeting_room_schedules_path
    else
      render "new"
    end
  end

  #edit
  def edit
    @schedule = @meeting_room.schedules.find(params[:id])
    commontator_thread_show(@schedule)
    @users_list = User.pluck(:email)
  end

  #update
  def update
    @schedule = @meeting_room.schedules.find(params[:id])
    @users_list = User.pluck(:email)

    if @schedule.update(schedule_params)
      UserMailer.send_mail(@schedule, @users_list).deliver_now
      redirect_to meeting_room_schedules_path
    else
      render "edit"
    end
  end

  # Destroy the project
  def destroy
    @schedule = @meeting_room.schedules.find(params[:id])
    if @schedule.destroy
      redirect_to meeting_room_schedules_path
    else
      render "new"
    end
  end

  private

  #set Meeting Room
  def set_meeting_room
    @meeting_room = MeetingRoom.find(params[:meeting_room_id])
  end

  #set schedule
  # def set_schedule
  #   @schedule = Schedule.find(params[:id])
  # end
  #set params
  def schedule_params
    params.require(:schedule).permit(:name, :agenda, :start_date, :start_time, :end_time, :add_users)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_date(date)
        date.strftime("%m/%d/%Y")
    end

    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")

    end
    def author_of(record)
        user_signed_in? && current_user.id == record.user_id
    end

    def admin?
        user_signed_in? && current_user.admin?
    end
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flasherror.html.erb
<div class = "container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<footer>

  <div class="footer-copyright text-center py-3">&copy; | Roman KC & Subash Khatri | Jyaasa - Meeting Room Scheduler <br>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1 animated infinite pulse delay-2s"> Meeting Room Scheduler</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if current_user %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active">
            <%= link_to 'Meeting Rooms', meeting_rooms_path, class: 'nav-link'%>
          </li>

          <li class="nav-item active">
            <%= link_to 'Schedules', all_schedules_path, class: 'nav-link'%>
          </li>

          <li class="nav-item dropdown mr-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user && current_user.admin%>
                <%= link_to 'Invitation',new_user_invitation_path, class: 'dropdown-item' %>
              <% end %>
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
            </div>
          </li>
      </div>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>GroupAMeetingRoomScheduler</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
</head>

<body>
  <%= render "layouts/header"%>
  <%= render "layouts/flasherror" %>

  <%= yield %>
</body>

</html>

app/views/meeting_rooms/_form.slim
p
  = form.label :name
  br/
  = form.text_field :name, class:'form-control col-auto'
p
  = form.label :description
  br/
  = form.text_area :description,class:'form-control col-auto'
p
  = form.submit class: 'btn btn-primary col-8 margin-left'

app/views/meeting_rooms/edit.slim
= render 'layouts/flasherror'
.container 
  h3 Edit Meeting Room
  = form_for @meeting_room, url: meeting_room_path(@meeting_room.id), method: :put do |f|
    = render(:partial => 'form', :locals => {:form => f})

app/views/meeting_rooms/index.slim
.container
  / div for each meeting room
  -@meeting_rooms.each do |room|
    .col-md-5
      = room.name
      .meeting_action
        / or current_user.create_user?
        -if admin?
          = link_to 'Edit',  edit_meeting_room_path(room), class: 'btn btn-outline-info margin-left'
          = link_to 'Book', new_meeting_room_schedule_path(room.id), class: 'btn btn-outline-info margin-left'
          = link_to 'Delete', meeting_room_path(room), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-info margin-left'
        -else 
          = link_to 'Book', new_meeting_room_schedule_path(room.id), class: 'btn btn-outine-info margin-left', class: 'btn btn-outline-info margin-left'
        
-if admin?
  br/
  br/
  = link_to "New Meeting Room", new_meeting_room_path,class: 'btn btn-info margin-left-center'

app/views/meeting_rooms/new.slim
= render 'layouts/flasherror'
.container 
  h3 Create New Project
  = form_for @meeting_room do |f|
    =render(:partial => 'form', :locals => {:form => f})

app/views/schedules/_bookform.slim
.form_item
  = form.label :name
  br/
  = form.text_field :name, class:'form-control col-auto'

.form_item
  = form.label :agenda
  / = commontator_thread(@schedule)
  br/
  = form.text_area :agenda,class:'form-control col-auto'

.form_item
  = form.label :start_date
  = render 'calendar'
  br/
  / form selection for start date
  = form.select :start_date,['2019-09-10','2019-09-11'],{},class:'form-control col-2'
  
/ .form_item
/   = form.label :end_date
/   br/
/   / form selection for start date
/   = form.select :end_date,['2019-09-11','2019-09-12'],{},class:'form-control col-2'

.form_item
  = form.label :start_time
  br/

  / form selection for start date
  = form.select :start_time,['10:00','11:00'],{},class:'form-control col-2'

.form_item
  = form.label :end_time
  br/
  / form selection for start date
  = form.select :end_time,['11:00','12:00'],{},class:'form-control col-2'

.form-item
  = form.label :add_users
  / select helper takes two options hashes, one for select, and the second for html options
  / (:TYPE, Categories.collect {|p| [ p.name, p.id ] },
  = form.select :add_users, options_for_select(@users_list),{ :multiple => true}, class:'form-control col-3'
  / - @users_list.each do |email|    
  /   = form.check_box :add_users, { multiple: true }, email
  /   label = email


.form_item
  = form.submit class: 'btn btn-dark col-8 margin-left'

app/views/schedules/_calendar.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                    <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/schedules/all_schedules.slim
table class = "table table-dark table-hover"
  tr
    th Name
    th Agenda
    th Meeting Room
    th Start Date
    th Start Time
    th End Time
    th Users

  -@schedules.each do |schedule|
    tr
      td = schedule.name
      td = schedule.agenda
      td = schedule.meeting_room.name
      td = readable_date(schedule.start_date)
      td = readable_time(schedule.start_time)
      td = readable_time(schedule.end_time)
      td = schedule.add_users

     

app/views/schedules/edit.slim
= render 'layouts/flasherror'
.container 
  h3 Edit Schedule
  / - binding.pry
  = form_for @schedule, url: meeting_room_schedule_path(@meeting_room.id, @schedule.id), method: :put do |f|
    = render(:partial => 'bookform', :locals => {:form => f})

app/views/schedules/index.slim
table class = "table table-dark table-hover"
  tr
    th Name
    th Agenda
    th Start Date
    th End Date
    th Start Time
    th End Time
    th Users

  -@meeting_room.schedules.each do |schedule|
    tr
      td = schedule.name
      td = schedule.agenda
      td = readable_date(schedule.start_date)
      td = readable_time(schedule.start_time)
      td = readable_time(schedule.end_time)
      / td = schedule.add_users

      / Only for creating users
      -if admin?
          td = link_to 'Show', meeting_room_schedule_path(meeting_room_id:@meeting_room.id, id: schedule.id), class: 'btn btn-info'
          td = link_to 'Edit', edit_meeting_room_schedule_path(meeting_room_id:@meeting_room.id, id: schedule.id), class: 'btn btn-info'
          td = link_to 'Delete', meeting_room_schedule_path(@meeting_room, schedule), method: :delete, data: {confirm: 'Are You sure ?'},class: 'btn btn-info'

app/views/schedules/new.slim
= render 'layouts/flasherror'
.container 
  h3 Create Schedule
  = form_for ([@meeting_room, @schedule]) do |f|
    =render(:partial => 'bookform', :locals => {:form => f})
    

app/views/schedules/show.slim
.container
	h3 Meeting Schedule Details
	p
	strong Name: 
	= @schedule.name
	p
	strong Agenda: 
	= @schedule.agenda
	p
	strong Start Date: 
	= readable_date(@schedule.start_date)
	p
	strong Start Time: 
	= readable_time(@schedule.start_time)
	p
	strong End Time: 
	= readable_time(@schedule.end_time)
	p
	strong Attendies: 
	= @schedule.add_users
	p
	strong Minutes: 
	= commontator_thread(@schedule)

= link_to 'Meeting Room', meeting_rooms_path, class: 'btn btn-info col-8 margin-left'  

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>